//! `cargo xtask bindgen`: regenerate crates/ferrite-sys/src/bindings_emery.rs
//! from the installed Pebble SDK.
//!
//! Requires libclang (Apple Command Line Tools suffice). Override the SDK
//! location with PEBBLE_SDK_ROOT if it is not in the default install path.

use std::path::PathBuf;
use std::process::ExitCode;

/// SDK version the committed bindings are pinned to. The firmware jump table
/// is index-based, so bindings must match the SDK the app links against.
const SDK_VERSION: &str = "4.17";

/// Emery platform defines, mirrored from the SDK's
/// `sdk-core/pebble/common/tools/pebble_sdk_platform.py`.
const EMERY_DEFINES: &[&str] = &[
    "-DPBL_PLATFORM_EMERY",
    "-DPBL_COLOR",
    "-DPBL_RECT",
    "-DPBL_MICROPHONE",
    "-DPBL_SMARTSTRAP",
    "-DPBL_SMARTSTRAP_POWER",
    "-DPBL_HEALTH",
    "-DPBL_COMPASS",
    "-DPBL_TOUCH",
    "-DPBL_RGB_BACKLIGHT",
    "-DPBL_SPEAKER",
    "-DPBL_DISPLAY_WIDTH=200",
    "-DPBL_DISPLAY_HEIGHT=228",
];

fn sdk_root() -> PathBuf {
    if let Ok(p) = std::env::var("PEBBLE_SDK_ROOT") {
        return PathBuf::from(p);
    }
    std::env::home_dir()
        .expect("cannot determine home directory")
        .join("Library/Application Support/Pebble SDK/SDKs")
        .join(SDK_VERSION)
}

pub fn run() -> ExitCode {
    let sdk = sdk_root();
    let emery_include = sdk.join("sdk-core/pebble/emery/include");
    let newlib_include = sdk.join("toolchain/arm-none-eabi/arm-none-eabi/include");
    let pebble_h = emery_include.join("pebble.h");

    for required in [&pebble_h, &newlib_include] {
        if !required.exists() {
            eprintln!(
                "error: {} not found.\nInstall Pebble SDK {} or set PEBBLE_SDK_ROOT.",
                required.display(),
                SDK_VERSION
            );
            return ExitCode::FAILURE;
        }
    }

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let stubs = manifest_dir.join("stubs");
    let out = manifest_dir.join("../ferrite-sys/src/bindings_emery.rs");

    let mut clang_args: Vec<String> = vec![
        "--target=thumbv7m-none-eabi".into(),
        // The SDK is built by arm-none-eabi-gcc, which defaults to AAPCS
        // short enums; clang does not. Without this, struct layouts with
        // enum-typed fields (e.g. Tuplet) are wrong.
        "-fshort-enums".into(),
        "-ffreestanding".into(),
        // Prevent time.h from being included by pebble.h. We define struct tm
        // with the extended Pebble fields in our pebble.h wrapper.
        "-D_TIME_H_".into(),
        "-Dtime_t=long".into(),
        "-Dclock_t=long".into(),
        format!("-I{}", stubs.display()),
        format!("-isystem{}", emery_include.display()),
        format!("-isystem{}", newlib_include.display()),
    ];
    clang_args.extend(EMERY_DEFINES.iter().map(|d| d.to_string()));

    let bindings = bindgen::Builder::default()
        .header(pebble_h.to_string_lossy())
        .use_core()
        .clang_args(&clang_args)
        .allowlist_file(".*/pebble\\.h")
        .allowlist_file(".*/pebble_fonts\\.h")
        .allowlist_file(".*/gcolor_definitions\\.h")
        // pebble.h redefines 'tm' struct from time.h and causes a fatal clang error.
        // Block everything time-related to work around the conflict.
        .blocklist_file(".*/time\\.h")
        .blocklist_type("tm")
        .blocklist_type("time_t")
        .blocklist_function("time")
        .blocklist_function("difftime")
        .blocklist_function("mktime")
        .blocklist_function("localtime")
        .blocklist_function("gmtime")
        .blocklist_function("strftime")
        .blocklist_function("strptime")
        .blocklist_function("asctime")
        .blocklist_function("ctime")
        .blocklist_function("clock")
        .blocklist_function("clock_gettime")
        .blocklist_function("clock_settime")
        .blocklist_function("timer_create")
        .blocklist_function("timer_delete")
        .blocklist_function("timer_getoverrun")
        .blocklist_function("timer_gettime")
        .blocklist_function("timer_settime")
        .blocklist_function("nanosleep")
        .default_enum_style(bindgen::EnumVariation::NewType {
            is_bitfield: false,
            is_global: false,
        })
        .prepend_enum_name(false)
        .derive_default(true)
        .layout_tests(false)
        .formatter(bindgen::Formatter::Prettyplease)
        .raw_line(format!(
            "// @generated by `cargo xtask bindgen` from Pebble SDK {SDK_VERSION} (emery).\n\
             // Do not edit by hand."
        ))
        .generate()
        .expect("bindgen failed");

    bindings.write_to_file(&out).expect("failed to write bindings");
    println!("wrote {}", out.display());
    ExitCode::SUCCESS
}
