//! `cargo xtask bindgen`: regenerate crates/ferrite-sys/src/bindings_emery.rs
//! from the installed Pebble SDK.
//!
//! Requires libclang (Apple Command Line Tools suffice). Override the SDK
//! location with PEBBLE_SDK_ROOT if it is not in the default install path.

use std::path::PathBuf;
use std::process::ExitCode;

/// SDK version the committed bindings are pinned to. The firmware jump table
/// is index-based, so bindings must match the SDK the app links against.
const SDK_VERSION: &str = "4.17";

/// Platform the bindings are generated for. Emitted into the generated file
/// so `ferrite-sys` re-exports it rather than restating it.
const PLATFORM: &str = "emery";

/// Emery platform defines, mirrored from the SDK's
/// `sdk-core/pebble/common/tools/pebble_sdk_platform.py`.
const EMERY_DEFINES: &[&str] = &[
    "-DPBL_PLATFORM_EMERY",
    "-DPBL_COLOR",
    "-DPBL_RECT",
    "-DPBL_MICROPHONE",
    "-DPBL_SMARTSTRAP",
    "-DPBL_SMARTSTRAP_POWER",
    "-DPBL_HEALTH",
    "-DPBL_COMPASS",
    "-DPBL_TOUCH",
    "-DPBL_RGB_BACKLIGHT",
    "-DPBL_SPEAKER",
    "-DPBL_DISPLAY_WIDTH=200",
    "-DPBL_DISPLAY_HEIGHT=228",
];

fn sdk_root() -> PathBuf {
    if let Ok(p) = std::env::var("PEBBLE_SDK_ROOT") {
        return PathBuf::from(p);
    }
    std::env::home_dir()
        .unwrap_or_default()
        .join("Library/Application Support/Pebble SDK/SDKs")
        .join(SDK_VERSION)
}

pub fn run() -> ExitCode {
    let sdk = sdk_root();
    let emery_include = sdk.join("sdk-core/pebble/emery/include");
    let newlib_include = sdk.join("toolchain/arm-none-eabi/arm-none-eabi/include");
    let pebble_h = emery_include.join("pebble.h");

    for required in [&pebble_h, &newlib_include] {
        if !required.exists() {
            eprintln!(
                "error: {} not found.\nInstall Pebble SDK {} or set PEBBLE_SDK_ROOT.",
                required.display(),
                SDK_VERSION
            );
            return ExitCode::FAILURE;
        }
    }

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let stubs = manifest_dir.join("stubs");
    let out = manifest_dir.join("../ferrite-sys/src/bindings_emery.rs");

    let mut clang_args: Vec<String> = vec![
        "--target=thumbv7m-none-eabi".into(),
        // The SDK is built by arm-none-eabi-gcc, which defaults to AAPCS
        // short enums; clang does not. Without this, struct layouts with
        // enum-typed fields (e.g. Tuplet) are wrong.
        "-fshort-enums".into(),
        "-ffreestanding".into(),
        // pebble.h includes <time.h> and then defines its OWN `struct tm`
        // (9 ints + int tm_gmtoff + char tm_zone[6], 48 bytes) plus its own
        // strftime/localtime/gmtime/mktime prototypes. Against newlib's
        // time.h that is a hard redefinition error -- real arm-none-eabi-gcc
        // fails on it too.
        //
        // These two defines are NOT our invention: they are exactly what the
        // SDK's own compiler config applies, so app C code sees Pebble's
        // struct tm and a 32-bit time_t rather than newlib's. Mirroring them
        // is what makes our bindings match the ABI the firmware was built
        // against. Source: sdk-core/pebble/<waf>/waflib/extras/pebble_sdk_gcc.py,
        // and confirmed present in examples/hello/build/c4che/emery_cache.py
        // CFLAGS for this very project.
        "-D_TIME_H_".into(),
        "-Dtime_t=long".into(),
        format!("-I{}", stubs.display()),
        format!("-I{}", emery_include.display()),
        format!("-I{}", newlib_include.display()),
    ];
    clang_args.extend(EMERY_DEFINES.iter().map(|d| d.to_string()));

    let bindings = bindgen::Builder::default()
        .header(pebble_h.to_string_lossy())
        .use_core()
        .clang_args(&clang_args)
        .allowlist_file(".*/pebble\\.h")
        .allowlist_file(".*/pebble_fonts\\.h")
        .allowlist_file(".*/gcolor_definitions\\.h")
        .default_enum_style(bindgen::EnumVariation::NewType {
            is_bitfield: false,
            is_global: false,
        })
        .prepend_enum_name(false)
        .derive_default(true)
        .layout_tests(false)
        // Rustfmt rather than Prettyplease so the committed output is already
        // in `cargo fmt` canonical form. With Prettyplease the two disagree,
        // so `cargo fmt --all --check` fails on generated code and running
        // `cargo fmt` would reformat a file that the next `cargo xtask
        // bindgen` immediately rewrites.
        .formatter(bindgen::Formatter::Rustfmt)
        .raw_line(format!(
            "// @generated by `cargo xtask bindgen` from Pebble SDK {SDK_VERSION} ({PLATFORM}).\n\
             // Do not edit by hand.\n\
             \n\
             /// SDK version these bindings were generated from. Emitted by the\n\
             /// generator so it cannot drift from the headers actually parsed --\n\
             /// the firmware jump table is index-based, so a consumer checking\n\
             /// compatibility needs the real value, not a hand-copied one.\n\
             pub const PEBBLE_SDK_VERSION: &str = \"{SDK_VERSION}\";\n\
             /// Platform these bindings were generated for.\n\
             pub const PEBBLE_SDK_PLATFORM: &str = \"{PLATFORM}\";\n\
             \n\
             /// The SDK compiles app C with `-Dtime_t=long`, so `time_t` is gone\n\
             /// before clang sees it and bindgen cannot emit the alias. Declared\n\
             /// here so callers have the name the SDK docs use.\n\
             pub type time_t = ::core::ffi::c_long;"
        ))
        .generate();

    let bindings = match bindings {
        Ok(b) => b,
        Err(e) => {
            eprintln!("error: bindgen failed: {e}");
            return ExitCode::FAILURE;
        }
    };

    if let Err(e) = bindings.write_to_file(&out) {
        eprintln!("error: could not write {}: {e}", out.display());
        return ExitCode::FAILURE;
    }
    println!("wrote {}", out.display());
    ExitCode::SUCCESS
}
