//! Generate Rust messageKeys constants from package.json.

use std::process::ExitCode;

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

/// Parse message keys from package.json, returning (name, numeric_id) tuples
/// numbered sequentially from 10000 in array order.
fn parse_message_keys(json: &str) -> Result<Vec<(String, u32)>> {
    let value: serde_json::Value = serde_json::from_str(json)?;

    let keys = value
        .get("pebble")
        .and_then(|p| p.get("messageKeys"))
        .and_then(|mk| mk.as_array())
        .ok_or("messageKeys not found in pebble section")?;

    let result = keys
        .iter()
        .enumerate()
        .map(|(i, k)| {
            let name = k.as_str().ok_or("messageKey is not a string")?;
            Ok((name.to_string(), 10000 + i as u32))
        })
        .collect::<Result<Vec<_>>>()?;

    Ok(result)
}

/// Emit a Rust module defining the messageKeys constants.
fn emit_module(keys: &[(String, u32)]) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `cargo xtask messagekeys` — DO NOT EDIT.\n");
    out.push_str("//!\n");
    out.push_str("//! Source: <path to package.json>\n");
    out.push_str("//! Regenerate: cargo xtask messagekeys <args>\n");
    out.push_str("//!\n");
    out.push_str("//! Values are assigned sequentially from 10000 in `messageKeys` array order.\n");
    out.push_str("//! The order IS the wire contract, shared with the phone-side JS. Append new\n");
    out.push_str("//! keys at the end; never insert or reorder.\n");
    out.push('\n');

    for (name, id) in keys {
        out.push_str(&format!("pub const {}: u32 = {};\n", name, id));
    }

    out.push('\n');
    out
}

pub fn run(args: &[String]) -> ExitCode {
    if args.is_empty() || matches!(args.first().map(String::as_str), Some("--help" | "-h")) {
        eprintln!("usage: cargo xtask messagekeys [--check] <package.json> <output.rs>");
        eprintln!("  Generates Rust messageKeys constants from package.json");
        eprintln!("  --check: verify output matches the existing file, exit nonzero if not");
        return if args.is_empty() {
            ExitCode::FAILURE
        } else {
            ExitCode::SUCCESS
        };
    }

    let (check_mode, package_path, output_path) =
        if args.first().map(String::as_str) == Some("--check") {
            if args.len() < 3 {
                eprintln!("error: --check requires <package.json> and <output.rs>");
                return ExitCode::FAILURE;
            }
            (true, &args[1], &args[2])
        } else {
            if args.len() < 2 {
                eprintln!("error: requires <package.json> and <output.rs>");
                return ExitCode::FAILURE;
            }
            (false, &args[0], &args[1])
        };

    // Read package.json
    let json_content = match std::fs::read_to_string(package_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("error: cannot read {}: {}", package_path, e);
            return ExitCode::FAILURE;
        }
    };

    // Parse and generate
    let keys = match parse_message_keys(&json_content) {
        Ok(k) => k,
        Err(e) => {
            eprintln!("error: cannot parse {}: {}", package_path, e);
            return ExitCode::FAILURE;
        }
    };

    let generated = emit_module(&keys);

    if check_mode {
        // Read existing file
        let existing = match std::fs::read_to_string(output_path) {
            Ok(c) => c,
            Err(e) => {
                eprintln!("error: --check mode: cannot read {}: {}", output_path, e);
                return ExitCode::FAILURE;
            }
        };

        if existing == generated {
            ExitCode::SUCCESS
        } else {
            eprintln!(
                "error: {} is out of date — run `cargo xtask messagekeys {} {}` to regenerate",
                output_path, package_path, output_path
            );
            ExitCode::FAILURE
        }
    } else {
        // Write output file
        if let Err(e) = std::fs::write(output_path, &generated) {
            eprintln!("error: cannot write {}: {}", output_path, e);
            return ExitCode::FAILURE;
        }
        ExitCode::SUCCESS
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"{
      "name": "fitter",
      "pebble": {
        "messageKeys": ["LAT", "LON", "CFG_PAUSE_SPEED"]
      }
    }"#;

    #[test]
    fn keys_are_numbered_sequentially_from_10000_in_array_order() {
        let keys = parse_message_keys(SAMPLE).unwrap();
        assert_eq!(
            keys,
            vec![
                ("LAT".to_string(), 10000),
                ("LON".to_string(), 10001),
                ("CFG_PAUSE_SPEED".to_string(), 10002),
            ]
        );
    }

    /// Array order IS the wire contract. This test is the reason the
    /// generator exists: a reordered array must produce different constants,
    /// so the --check gate catches it before it ships.
    #[test]
    fn reordering_the_array_changes_the_numbering() {
        let reordered = SAMPLE.replace(
            r#"["LAT", "LON", "CFG_PAUSE_SPEED"]"#,
            r#"["LON", "LAT", "CFG_PAUSE_SPEED"]"#,
        );
        let keys = parse_message_keys(&reordered).unwrap();
        assert_eq!(keys[0], ("LON".to_string(), 10000));
        assert_eq!(keys[1], ("LAT".to_string(), 10001));
    }

    #[test]
    fn missing_message_keys_is_an_error_not_an_empty_module() {
        assert!(parse_message_keys(r#"{"pebble": {}}"#).is_err());
        assert!(parse_message_keys(r#"{}"#).is_err());
    }

    #[test]
    fn emitted_module_is_deterministic_and_declares_consts() {
        let keys = parse_message_keys(SAMPLE).unwrap();
        let out = emit_module(&keys);
        assert_eq!(out, emit_module(&keys), "emission must be deterministic");
        assert!(out.contains("pub const LAT: u32 = 10000;"));
        assert!(out.contains("pub const CFG_PAUSE_SPEED: u32 = 10002;"));
        assert!(out.contains("DO NOT EDIT"), "generated files must say so");
    }

    #[test]
    fn emitted_module_ends_with_a_newline() {
        let keys = parse_message_keys(SAMPLE).unwrap();
        assert!(emit_module(&keys).ends_with('\n'));
    }
}
