//! Generate Rust messageKeys constants from package.json.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

/// Determine whether two repository roots are the same.
///
/// This is the core predicate for deciding which regeneration command to emit.
/// Returns true if they are the same repo, false otherwise.
fn same_repo_root(xtask_repo: &Path, output_repo: &Path) -> bool {
    xtask_repo == output_repo
}

/// Determine whether the output path is in the same git repository as xtask itself.
///
/// Returns true if output is in xtask's repo, false if it's in a different repo.
/// This predicate is used to decide whether `cargo xtask messagekeys` will resolve
/// when run from the output path's repository root.
fn is_output_in_xtask_repo(output_path: &str) -> Result<bool> {
    // Find xtask's own repository root from the manifest directory.
    // env!("CARGO_MANIFEST_DIR") is a compile-time constant referring to the
    // directory containing this crate's Cargo.toml — no runtime cwd dependence.
    let xtask_manifest_dir = env!("CARGO_MANIFEST_DIR");
    let xtask_repo_root = find_repo_root(xtask_manifest_dir)?;

    // Find the repository root of the output path.
    let output_repo_root = find_repo_root(output_path)?;

    // They must be the same for a simple `cargo xtask` command to work.
    Ok(same_repo_root(&xtask_repo_root, &output_repo_root))
}

/// Find the git repository root by walking up from a given path.
/// If the path doesn't exist, canonicalize its parent instead.
fn find_repo_root(from: &str) -> Result<PathBuf> {
    let path_buf = PathBuf::from(from);
    let mut path = if path_buf.exists() {
        path_buf.canonicalize()?
    } else {
        // Path doesn't exist; canonicalize parent and rejoin the name.
        let mut parent = path_buf.parent().ok_or("path has no parent")?;
        let parent_buf;
        if parent.as_os_str().is_empty() {
            // Bare filename; use current directory as parent.
            parent_buf = Path::new(".");
            parent = parent_buf;
        }
        let parent_canon = parent.canonicalize()?;
        if let Some(name) = path_buf.file_name() {
            parent_canon.join(name)
        } else {
            parent_canon
        }
    };
    loop {
        if path.join(".git").exists() {
            return Ok(path);
        }
        if !path.pop() {
            return Err("not in a git repository".into());
        }
    }
}

/// Compute a relative path from `base` to `target`.
/// `base` must be a directory (and must exist). `target` may be a file that
/// does not exist yet — we canonicalize its parent and rejoin the filename.
fn pathdiff(base: &Path, target: &str) -> Result<String> {
    let base_canon = base.canonicalize()?;
    let target_path = PathBuf::from(target);

    // If target exists, canonicalize it directly. Otherwise canonicalize the parent.
    let target_canon = if target_path.exists() {
        target_path.canonicalize()?
    } else {
        let mut parent = target_path.parent().ok_or("target has no parent")?;
        // Bare filename has an empty parent; treat it as current directory.
        if parent.as_os_str().is_empty() {
            parent = Path::new(".");
        }
        let parent_canon = parent.canonicalize()?;
        parent_canon.join(target_path.file_name().ok_or("target has no filename")?)
    };

    // Simple relative path: start from base, strip matching prefix.
    if let Ok(rel) = target_canon.strip_prefix(&base_canon) {
        Ok(rel.to_string_lossy().to_string())
    } else {
        // Fall back to absolute if no common prefix (shouldn't happen in git repos).
        Ok(target_canon.to_string_lossy().to_string())
    }
}

/// Parse message keys from package.json, returning (name, numeric_id) tuples
/// numbered sequentially from 10000 in array order.
fn parse_message_keys(json: &str) -> Result<Vec<(String, u32)>> {
    let value: serde_json::Value = serde_json::from_str(json)?;

    let keys = value
        .get("pebble")
        .and_then(|p| p.get("messageKeys"))
        .and_then(|mk| mk.as_array())
        .ok_or("messageKeys not found in pebble section")?;

    let result = keys
        .iter()
        .enumerate()
        .map(|(i, k)| {
            let name = k.as_str().ok_or("messageKey is not a string")?;
            Ok((name.to_string(), 10000 + i as u32))
        })
        .collect::<Result<Vec<_>>>()?;

    Ok(result)
}

/// Emit a Rust module defining the messageKeys constants.
///
/// `source_path` is the repo-relative path to package.json (so the output is
/// identical across checkouts). `regen_cmd` is the command to run to regenerate.
fn emit_module(keys: &[(String, u32)], source_path: &str, regen_cmd: &str) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `cargo xtask messagekeys` — DO NOT EDIT.\n");
    out.push_str("//!\n");
    out.push_str(&format!("//! Source: {}\n", source_path));
    out.push_str(&format!("//! Regenerate: {}\n", regen_cmd));
    out.push_str("//!\n");
    out.push_str("//! Values are assigned sequentially from 10000 in `messageKeys` array order.\n");
    out.push_str("//! The order IS the wire contract, shared with the phone-side JS. Append new\n");
    out.push_str("//! keys at the end; never insert or reorder.\n");
    out.push('\n');

    for (name, id) in keys {
        out.push_str(&format!("pub const {}: u32 = {};\n", name, id));
    }

    out
}

pub fn run(args: &[String]) -> ExitCode {
    if args.is_empty() || matches!(args.first().map(String::as_str), Some("--help" | "-h")) {
        eprintln!("usage: cargo xtask messagekeys [--check] <package.json> <output.rs>");
        eprintln!("  Generates Rust messageKeys constants from package.json");
        eprintln!("  --check: verify output matches the existing file, exit nonzero if not");
        return if args.is_empty() {
            ExitCode::FAILURE
        } else {
            ExitCode::SUCCESS
        };
    }

    let (check_mode, package_path, output_path) =
        if args.first().map(String::as_str) == Some("--check") {
            if args.len() < 3 {
                eprintln!("error: --check requires <package.json> and <output.rs>");
                return ExitCode::FAILURE;
            }
            (true, &args[1], &args[2])
        } else {
            if args.len() < 2 {
                eprintln!("error: requires <package.json> and <output.rs>");
                return ExitCode::FAILURE;
            }
            (false, &args[0], &args[1])
        };

    // Read package.json
    let json_content = match std::fs::read_to_string(package_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("error: cannot read {}: {}", package_path, e);
            return ExitCode::FAILURE;
        }
    };

    // Parse and generate
    let keys = match parse_message_keys(&json_content) {
        Ok(k) => k,
        Err(e) => {
            eprintln!("error: cannot parse {}: {}", package_path, e);
            return ExitCode::FAILURE;
        }
    };

    // Compute repo-relative paths for the generated file header.
    // This makes the output identical across checkouts, which matters
    // for a --check gate that compares files.
    let repo_root = match find_repo_root(package_path) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("error: cannot find repo root: {}", e);
            return ExitCode::FAILURE;
        }
    };
    let rel_package_path = match pathdiff(&repo_root, package_path) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("error: cannot compute relative path: {}", e);
            return ExitCode::FAILURE;
        }
    };
    let rel_output_path = match pathdiff(&repo_root, output_path) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("error: cannot compute relative path: {}", e);
            return ExitCode::FAILURE;
        }
    };

    // Determine if output is in the same git repo as xtask itself.
    // This decision must depend only on the arguments (output_path),
    // not on the process working directory. env!("CARGO_MANIFEST_DIR")
    // is a compile-time constant, so this is deterministic.
    let in_xtask_repo = match is_output_in_xtask_repo(output_path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("error: cannot determine repo relationship: {}", e);
            return ExitCode::FAILURE;
        }
    };

    let regen_cmd = if in_xtask_repo {
        // Output is in the same repo as xtask: a simple command will work.
        format!(
            "cargo xtask messagekeys {} {}",
            rel_package_path, rel_output_path
        )
    } else {
        // Output is in a different repo: emit a note pointing to the authoritative gate command.
        "See scripts/check.sh for the regeneration command".to_string()
    };

    let generated = emit_module(&keys, &rel_package_path, &regen_cmd);

    if check_mode {
        // Read existing file
        let existing = match std::fs::read_to_string(output_path) {
            Ok(c) => c,
            Err(e) => {
                eprintln!("error: --check mode: cannot read {}: {}", output_path, e);
                return ExitCode::FAILURE;
            }
        };

        if existing == generated {
            ExitCode::SUCCESS
        } else {
            eprintln!(
                "error: {} is out of date — run `cargo xtask messagekeys {} {}` to regenerate",
                output_path, package_path, output_path
            );
            ExitCode::FAILURE
        }
    } else {
        // Write output file
        if let Err(e) = std::fs::write(output_path, &generated) {
            eprintln!("error: cannot write {}: {}", output_path, e);
            return ExitCode::FAILURE;
        }
        ExitCode::SUCCESS
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"{
      "name": "fitter",
      "pebble": {
        "messageKeys": ["LAT", "LON", "CFG_PAUSE_SPEED"]
      }
    }"#;

    #[test]
    fn keys_are_numbered_sequentially_from_10000_in_array_order() {
        let keys = parse_message_keys(SAMPLE).unwrap();
        assert_eq!(
            keys,
            vec![
                ("LAT".to_string(), 10000),
                ("LON".to_string(), 10001),
                ("CFG_PAUSE_SPEED".to_string(), 10002),
            ]
        );
    }

    /// Array order IS the wire contract. This test is the reason the
    /// generator exists: a reordered array must produce different constants,
    /// so the --check gate catches it before it ships.
    #[test]
    fn reordering_the_array_changes_the_numbering() {
        let reordered = SAMPLE.replace(
            r#"["LAT", "LON", "CFG_PAUSE_SPEED"]"#,
            r#"["LON", "LAT", "CFG_PAUSE_SPEED"]"#,
        );
        let keys = parse_message_keys(&reordered).unwrap();
        assert_eq!(keys[0], ("LON".to_string(), 10000));
        assert_eq!(keys[1], ("LAT".to_string(), 10001));
    }

    #[test]
    fn missing_message_keys_is_an_error_not_an_empty_module() {
        assert!(parse_message_keys(r#"{"pebble": {}}"#).is_err());
        assert!(parse_message_keys(r#"{}"#).is_err());
    }

    #[test]
    fn emitted_module_is_deterministic_and_declares_consts() {
        let keys = parse_message_keys(SAMPLE).unwrap();
        let source = "package.json";
        let regen = "cargo xtask messagekeys package.json app/src/message_keys.rs";
        let out = emit_module(&keys, source, regen);
        assert_eq!(
            out,
            emit_module(&keys, source, regen),
            "emission must be deterministic"
        );
        assert!(out.contains("pub const LAT: u32 = 10000;"));
        assert!(out.contains("pub const CFG_PAUSE_SPEED: u32 = 10002;"));
        assert!(out.contains("DO NOT EDIT"), "generated files must say so");
    }

    #[test]
    fn emitted_module_ends_with_a_newline() {
        let keys = parse_message_keys(SAMPLE).unwrap();
        let out = emit_module(
            &keys,
            "package.json",
            "cargo xtask messagekeys package.json out.rs",
        );
        assert!(out.ends_with('\n'));
        // Regression: must not end with double newline (rustfmt would remove it).
        assert!(!out.ends_with("\n\n"), "must not end with double newline");
    }

    #[test]
    fn emitted_module_header_contains_real_paths() {
        let keys = parse_message_keys(SAMPLE).unwrap();
        let source = "path/to/package.json";
        let regen = "cargo xtask messagekeys path/to/package.json app/src/message_keys.rs";
        let out = emit_module(&keys, source, regen);
        assert!(out.contains(&format!("Source: {}", source)));
        assert!(out.contains(&format!("Regenerate: {}", regen)));
    }

    #[test]
    fn pathdiff_handles_nonexistent_target_file() {
        use std::fs;

        // Create a temp directory with a known structure
        let temp_base = std::env::temp_dir().join("messagekeys_test");
        let _ = fs::remove_dir_all(&temp_base);
        fs::create_dir_all(&temp_base).expect("create temp base");

        let subdir = temp_base.join("subdir");
        fs::create_dir(&subdir).expect("create subdir");

        // Target file does not exist yet, but its parent does
        let nonexistent = subdir.join("output.rs");
        assert!(!nonexistent.exists());

        // Should still compute a relative path without error
        let rel = super::pathdiff(&temp_base, nonexistent.to_str().unwrap())
            .expect("pathdiff succeeds even when target does not exist");

        // The relative path should point to the nonexistent file
        assert_eq!(rel, "subdir/output.rs");

        // Clean up
        let _ = fs::remove_dir_all(&temp_base);
    }

    #[test]
    fn pathdiff_handles_bare_filename_with_no_directory() {
        use std::env;
        use std::fs;

        // Save the current directory to restore it later
        let saved_dir = env::current_dir().expect("get current dir");

        // Create a temp directory and change to it
        let temp_base = std::env::temp_dir().join("messagekeys_bare_test");
        let _ = fs::remove_dir_all(&temp_base);
        fs::create_dir_all(&temp_base).expect("create temp base");

        env::set_current_dir(&temp_base).expect("change to temp dir");

        // Test a bare filename (no directory component)
        let rel =
            super::pathdiff(&temp_base, "output.rs").expect("pathdiff succeeds for bare filename");

        // The relative path should be the filename itself
        assert_eq!(rel, "output.rs");

        // Restore original directory and clean up
        let _ = env::set_current_dir(&saved_dir);
        let _ = fs::remove_dir_all(&temp_base);
    }

    #[test]
    fn same_repo_root_compares_paths_correctly() {
        use std::path::Path;

        let repo_a = Path::new("/path/to/repo/a");
        let repo_b = Path::new("/path/to/repo/b");
        let repo_a_again = Path::new("/path/to/repo/a");

        // Same path should be considered the same repo
        assert!(super::same_repo_root(repo_a, repo_a_again));

        // Different paths should be considered different repos
        assert!(!super::same_repo_root(repo_a, repo_b));

        // This test demonstrates the regression: if the old code had checked
        // whether the output repo root matches the package repo root (instead of
        // the xtask repo root), it would incorrectly conclude that output in
        // /path/to/repo/b is in the same repo as xtask in /path/to/repo/a.
        // This test ensures the predicate only returns true for actual matches.
    }
}
