//! Raw FFI bindings to the rePebble SDK.
//!
//! `bindings_emery` is machine-generated by `cargo xtask bindgen` — never
//! hand-edited. This file adds only Rust ports of function-like C macros
//! (which bindgen cannot generate) and compile-time layout assertions.

#![no_std]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

/// SDK version the committed bindings were generated from.
pub const PEBBLE_SDK_VERSION: &str = "4.17";
/// Platform the committed bindings were generated for.
pub const PEBBLE_SDK_PLATFORM: &str = "emery";

#[allow(nonstandard_style, unused, clippy::all)]
pub mod bindings_emery;

pub use bindings_emery::*;

// --- Ports of C constructor macros (pebble.h) ---

pub const fn GPoint(x: i16, y: i16) -> GPoint {
    GPoint { x, y }
}

pub const fn GSize(w: i16, h: i16) -> GSize {
    GSize { w, h }
}

pub const fn GRect(x: i16, y: i16, w: i16, h: i16) -> GRect {
    GRect {
        origin: GPoint(x, y),
        size: GSize(w, h),
    }
}

// --- Ports of color macros (gcolor_definitions.h) ---

/// C: `GColorFromRGBA(r, g, b, a)`. Each channel is truncated to 2 bits.
pub const fn GColorFromRGBA(red: u8, green: u8, blue: u8, alpha: u8) -> GColor8 {
    GColor8 {
        argb: ((alpha >> 6) << 6) | ((red >> 6) << 4) | ((green >> 6) << 2) | (blue >> 6),
    }
}

/// C: `GColorFromRGB(r, g, b)` — fully opaque.
pub const fn GColorFromRGB(red: u8, green: u8, blue: u8) -> GColor8 {
    GColorFromRGBA(red, green, blue, 255)
}

/// C: `GColorFromHEX(0xRRGGBB)`.
pub const fn GColorFromHEX(v: u32) -> GColor8 {
    GColorFromRGB(
        ((v >> 16) & 0xff) as u8,
        ((v >> 8) & 0xff) as u8,
        (v & 0xff) as u8,
    )
}

// --- Named colors (transcribed from gcolor_definitions.h) ---

pub const GColorBlack: GColor8 = GColor8 { argb: 0b1100_0000 };
pub const GColorOxfordBlue: GColor8 = GColor8 { argb: 0b1100_0001 };
pub const GColorDukeBlue: GColor8 = GColor8 { argb: 0b1100_0010 };
pub const GColorBlue: GColor8 = GColor8 { argb: 0b1100_0011 };
pub const GColorDarkGreen: GColor8 = GColor8 { argb: 0b1100_0100 };
pub const GColorMidnightGreen: GColor8 = GColor8 { argb: 0b1100_0101 };
pub const GColorCobaltBlue: GColor8 = GColor8 { argb: 0b1100_0110 };
pub const GColorBlueMoon: GColor8 = GColor8 { argb: 0b1100_0111 };
pub const GColorIslamicGreen: GColor8 = GColor8 { argb: 0b1100_1000 };
pub const GColorJaegerGreen: GColor8 = GColor8 { argb: 0b1100_1001 };
pub const GColorTiffanyBlue: GColor8 = GColor8 { argb: 0b1100_1010 };
pub const GColorVividCerulean: GColor8 = GColor8 { argb: 0b1100_1011 };
pub const GColorGreen: GColor8 = GColor8 { argb: 0b1100_1100 };
pub const GColorMalachite: GColor8 = GColor8 { argb: 0b1100_1101 };
pub const GColorMediumSpringGreen: GColor8 = GColor8 { argb: 0b1100_1110 };
pub const GColorCyan: GColor8 = GColor8 { argb: 0b1100_1111 };
pub const GColorBulgarianRose: GColor8 = GColor8 { argb: 0b1101_0000 };
pub const GColorImperialPurple: GColor8 = GColor8 { argb: 0b1101_0001 };
pub const GColorIndigo: GColor8 = GColor8 { argb: 0b1101_0010 };
pub const GColorElectricUltramarine: GColor8 = GColor8 { argb: 0b1101_0011 };
pub const GColorArmyGreen: GColor8 = GColor8 { argb: 0b1101_0100 };
pub const GColorDarkGray: GColor8 = GColor8 { argb: 0b1101_0101 };
pub const GColorLiberty: GColor8 = GColor8 { argb: 0b1101_0110 };
pub const GColorVeryLightBlue: GColor8 = GColor8 { argb: 0b1101_0111 };
pub const GColorKellyGreen: GColor8 = GColor8 { argb: 0b1101_1000 };
pub const GColorMayGreen: GColor8 = GColor8 { argb: 0b1101_1001 };
pub const GColorCadetBlue: GColor8 = GColor8 { argb: 0b1101_1010 };
pub const GColorPictonBlue: GColor8 = GColor8 { argb: 0b1101_1011 };
pub const GColorBrightGreen: GColor8 = GColor8 { argb: 0b1101_1100 };
pub const GColorScreaminGreen: GColor8 = GColor8 { argb: 0b1101_1101 };
pub const GColorMediumAquamarine: GColor8 = GColor8 { argb: 0b1101_1110 };
pub const GColorElectricBlue: GColor8 = GColor8 { argb: 0b1101_1111 };
pub const GColorDarkCandyAppleRed: GColor8 = GColor8 { argb: 0b1110_0000 };
pub const GColorJazzberryJam: GColor8 = GColor8 { argb: 0b1110_0001 };
pub const GColorPurple: GColor8 = GColor8 { argb: 0b1110_0010 };
pub const GColorVividViolet: GColor8 = GColor8 { argb: 0b1110_0011 };
pub const GColorWindsorTan: GColor8 = GColor8 { argb: 0b1110_0100 };
pub const GColorRoseVale: GColor8 = GColor8 { argb: 0b1110_0101 };
pub const GColorPurpureus: GColor8 = GColor8 { argb: 0b1110_0110 };
pub const GColorLavenderIndigo: GColor8 = GColor8 { argb: 0b1110_0111 };
pub const GColorLimerick: GColor8 = GColor8 { argb: 0b1110_1000 };
pub const GColorBrass: GColor8 = GColor8 { argb: 0b1110_1001 };
pub const GColorLightGray: GColor8 = GColor8 { argb: 0b1110_1010 };
pub const GColorBabyBlueEyes: GColor8 = GColor8 { argb: 0b1110_1011 };
pub const GColorSpringBud: GColor8 = GColor8 { argb: 0b1110_1100 };
pub const GColorInchworm: GColor8 = GColor8 { argb: 0b1110_1101 };
pub const GColorMintGreen: GColor8 = GColor8 { argb: 0b1110_1110 };
pub const GColorCeleste: GColor8 = GColor8 { argb: 0b1110_1111 };
pub const GColorRed: GColor8 = GColor8 { argb: 0b1111_0000 };
pub const GColorFolly: GColor8 = GColor8 { argb: 0b1111_0001 };
pub const GColorFashionMagenta: GColor8 = GColor8 { argb: 0b1111_0010 };
pub const GColorMagenta: GColor8 = GColor8 { argb: 0b1111_0011 };
pub const GColorOrange: GColor8 = GColor8 { argb: 0b1111_0100 };
pub const GColorSunsetOrange: GColor8 = GColor8 { argb: 0b1111_0101 };
pub const GColorBrilliantRose: GColor8 = GColor8 { argb: 0b1111_0110 };
pub const GColorShockingPink: GColor8 = GColor8 { argb: 0b1111_0111 };
pub const GColorChromeYellow: GColor8 = GColor8 { argb: 0b1111_1000 };
pub const GColorRajah: GColor8 = GColor8 { argb: 0b1111_1001 };
pub const GColorMelon: GColor8 = GColor8 { argb: 0b1111_1010 };
pub const GColorRichBrilliantLavender: GColor8 = GColor8 { argb: 0b1111_1011 };
pub const GColorYellow: GColor8 = GColor8 { argb: 0b1111_1100 };
pub const GColorIcterine: GColor8 = GColor8 { argb: 0b1111_1101 };
pub const GColorPastelYellow: GColor8 = GColor8 { argb: 0b1111_1110 };
pub const GColorWhite: GColor8 = GColor8 { argb: 0b1111_1111 };
pub const GColorClear: GColor8 = GColor8 { argb: 0b0000_0000 };

// --- Compile-time layout assertions for hazard structs ---
//
// Evaluated only when compiling for the watch target: they pin the ABI facts
// the safe wrappers rely on (packed structs, 1-byte GColor, short enums).
// If `cargo xtask bindgen` ever regenerates with wrong clang flags (e.g.
// missing -fshort-enums), these fail the build for the target.
#[cfg(target_arch = "arm")]
const _: () = {
    use core::mem::size_of;

    // Plan-specified assertions
    assert!(size_of::<GColor8>() == 1);
    assert!(size_of::<GPoint>() == 4);
    assert!(size_of::<GSize>() == 4);
    assert!(size_of::<GRect>() == 8);
    // packed: u32 key + TupleType:8 bitfield + u16 length (+ empty FAM)
    assert!(size_of::<Tuple>() == 7);
    // packed: 3 x i16 + bool + unaligned u64 timestamp
    assert!(size_of::<AccelData>() == 15);
    // short enums: 1 byte when values fit ...
    assert!(size_of::<GTextAlignment>() == 1);
    assert!(size_of::<TimeUnits>() == 1);
    assert!(size_of::<ButtonId>() == 1);
    // ... but 2 bytes for AppMessageResult (APP_MSG_INTERNAL_ERROR = 1 << 15)
    assert!(size_of::<AppMessageResult>() == 2);

    // Additional assertion for struct tm (pebble.h defines its own, not newlib's)
    // Measured from real arm-none-eabi-gcc with SDK's own CFLAGS:
    // sizeof(tm) == 48, offset_of(tm, tm_gmtoff) == 36, offset_of(tm, tm_zone) == 40
    assert!(size_of::<tm>() == 48);
};
